### ISSUE TITLE
Make upload work for arbitrary directories and files

### ISSUE THREAD

**Issue by dostuffthatmatters** [tum-esm/pyra#112]
Both upload and Helios directory are expected to have the format:

```
📁 <IFG OUTPOUT DIR>
    📁 YYYYMMDD
        📄 file 1
        📄 file 2
        📄 ...
    📁 YYYYMMDD
        📄 file 1
        📄 file 2
        📄 ...
```

This could be extended to arbitrary directories in this format. Every team will have some kind of local data generation logic. All of this data could be uploaded using the upload client.

We don't have to enforce a set of data sources and have less effort in the implementation. Currently, the upload-config looks like this:

```json
{
    "host": "1.2.3.4",
    "user": "...",
    "password": "...",
    "upload_ifgs": false,
    "src_directory_ifgs": "...",
    "dst_directory_ifgs": "...",
    "remove_src_ifgs_after_upload": false,
    "upload_helios": false,
    "dst_directory_helios": "...",
    "remove_src_helios_after_upload": true
}
```

A generalized upload config could look like:

```json
{
    "host": "1.2.3.4",
    "user": "...",
    "password": "...",
    "upload_items": [
        {
            "name": "helios",
            "active": false,
            "src": "...",
            "dst": "...",
            "remove_after_upload": false
        },
        {
            "name": "interferograms",
            "active": false,
            "src": "...",
            "dst": "...",
            "remove_after_upload": false
        }
    ]
}

```

Additionally, this should work for daily files, not only daily directories:

```
📁 <SRC DIR>
    📄 20220101-datalogger.txt
    📄 20220101-other-file.txt
    📄 20220102-datalogger.txt
    📄 20220102-other-file.txt
```

**Comment by dostuffthatmatters** [comment]
@patrickjaigner I want to move the upload client into a separate repository. With this feature, it will get even more complicated and make the Pyra codebase even bigger. Since it is a very general problem, having it separate means it can be tested, documented and released independently. In the current state it is not reusable by other projects and makes both sides (Pyra and the upload client) worse because of unnecessary complexity within Pyra itself.

**Comment by patrickjaigner** [comment]
@dostuffthatmatters it looks like the upload client is becoming it‘s own standalone feature. Go ahead an move it to another tum-esm repository if you think that helps. 

Do we already have non-Pyra use cases lined up?

**Comment by dostuffthatmatters** [comment]
> Go ahead an move it to another tum-esm repository if you think that helps.

Yes, will of course be also under tum-esm and heavily link towards Pyra. Will make it easier to manage both this tool and Pyra itself.

> Do we already have non-Pyra use cases lined up?

Not yet. But I looked at other options (rsync, etc.) again with fresh eyes and still have not found another tool that does what we want. Inside I could replace SCP with rsync or another tool, but the logic of "removal with checksums", "only considering past dates", "marking upload as incomplete", "logging", would require a similar amount of logic around any replacement for the internal copy mechanism.

**Comment by dostuffthatmatters** [comment]
Tracked in #193
