### ISSUE TITLE
Use a TUM domain for the documentation

### ISSUE THREAD

**Issue by dostuffthatmatters** [tum-esm/pyra#137]
Instead of `pyra-4-documentation.netlify.app` use a tum domain like `pyra.esm.ee.cit.tum.de` or `pyra.esm.cit.tum.de`.

- [x] Choose domain
- [x] Ask TUM IT Officers
- [x] Send DNS records
- [x] Check whether TLS Certificate has been renewed

**Comment by dostuffthatmatters** [comment]
@patrickjaigner which domain do you like more?

**Comment by patrickjaigner** [comment]
pyra.esm.cit.tum.de

**Comment by dostuffthatmatters** [comment]
`pyra.esm.ei.tum.de` it is because `cit.tum.de` domains cannot be set yet.
