### ISSUE TITLE
Some Helios cameras don't accept new settings

### ISSUE THREAD

**Issue by dostuffthatmatters** [tum-esm/pyra#167]
<img width="826" alt="Screenshot 2023-05-23 at 13 15 21" src="https://github.com/tum-esm/pyra/assets/29046316/705e05d1-7f79-4b85-97ee-04e064f82070">

Problem: this is blocking measurements
Solution: Only raise assertion errors on exposure setting (the most important) but only warn on the others.

**Comment by dostuffthatmatters** [comment]
The solution is this: I will only log a warning, when the camera did not accept a particular setting. However, instead of only sending all settings at the initialization, I will now send all settings on every update of the exposure (every 3 minutes). With this, Helios will not block everything else just because the camera communication is not fully working, but will try it again every 3 minutes.

**Comment by patrickjaigner** [comment]
This makes sense. A solution could also be a retry functionality, but I agree that a 3-minute cycle should be good enough and makes the code easier.
