### ISSUE TITLE
Mc04 station on 27.05 around 6:50am UTC showed PLC communication issues

### ISSUE THREAD

**Issue by patrickjaigner** [tum-esm/pyra#168]
The station reported that it can not write "sync to tracker" to the PLC. This was present for multiple cycles. 
Meanwhile, it was able to read the latest state from the PLC.

A way to fix it manually was to send a "move cover to x" command and afterward send "sync to tracker" again.

TODO: analyse why this happens

**Comment by dostuffthatmatters** [comment]
Closed due to inactivity
