### ISSUE TITLE
CamTracker not closing down after manual stop (4.0.8)

### ISSUE THREAD

**Issue by patrickjaigner** [tum-esm/pyra#170]
During my manual start and stops on Ma01 on 27.05.2023 I saw that CamTracker is not properly shutting down compared to version 4.0.7.

TODO: needs additional analysis.

**Comment by dostuffthatmatters** [comment]
This is not an issue with either `4.0.7` or `4.0.8`, it has persisted since at least `4.0.6`: https://github.com/tum-esm/pyra/compare/v4.0.6...integration-4.0.8#diff-8c0d2fdeedda01ddf781e8e00a65657b6878dad56d1e9900dae1f961e20361ea

**Comment by dostuffthatmatters** [comment]
I could not reproduce it. It was doing measurements in automatic mode, then I switched to manual mode, and then I clicked "stop". Then CamTracker closed.

@patrickjaigner Could you show me a video of that happening?

**Comment by patrickjaigner** [comment]
I retested it. It worked for me now. Maybe I was too impatient. 

-> Closed without action
