### ISSUE TITLE
Some modules are never executed when errors persist

### ISSUE THREAD

**Issue by dostuffthatmatters** [tum-esm/pyra#173]
Here is the order of how the different modules are executed: https://github.com/tum-esm/pyra/blob/dd29baedbd4c575ddbe6c275ba484daab15ae2b1/packages/core/main.py#L99-L105 When one module raises an Exception, none of the modules after that will be executed. So if the enclosure or CamTracker has an error, the OPUS-module will never be executed (so OPUS will never be started or stopped accordingly).

**Solution:** Since modules 2 to 5 depend on 1 but not on each other, we could move the processing of any exception after all of them (2 to 5) have been executed. Then we would still toggle OPUS/CamTracker correctly and check for battery state etc. even when the enclosure has issues. The emailing logic (occurred, resolved) will not be affected.

**Comment by patrickjaigner** [comment]
@dostuffthatmatters thanks for the idea. I agree that this should improve the process.
