### ISSUE TITLE
Migrate to Pydantic

### ISSUE THREAD

**Issue by dostuffthatmatters** [tum-esm/pyra#174]
The current way of validating the different JSON objects is very bad (combination of Ceberus and Pydantic). Fully moving to Pydantic will make future changes significantly easier.

**Comment by dostuffthatmatters** [comment]
@patrickjaigner this does not change anything about the validation logic. It just makes the codebase tremendously simpler.

**Comment by patrickjaigner** [comment]
@dostuffthatmatters I agree, no concerns.
