### ISSUE TITLE
Upload connection error causes Pyra to stall

### ISSUE THREAD

**Issue by csam1853** [tum-esm/pyra#181]
### Descriptions

<img width="1126" alt="image" src="https://github.com/tum-esm/pyra/assets/103441740/5fe56c2f-e5f8-4af3-9745-01277b5adeea">

Due to an internet connection error of the VPN client, Pyra stopped to go any further except the upload-loop. Although conditions were bad, the cover opened up on its own because it followed the cam tracker.

It is also recommended, that the upload time should not overlap with the measurement times.

After ending and restarting the Pyra process and disabling the automatic upload it worked again.

### Pyra Version

4.0.7

**Comment by dostuffthatmatters** [comment]
Interesting. For that reason the upload actually runs in a thread and should not affect the main loop (same as Helios).

I will investigate.

Thank you for the report.

**Comment by dostuffthatmatters** [comment]
Tracked in #193

**Comment by dostuffthatmatters** [comment]
This likely happened, because the thread was somehow not set to run as a daemon. This has been fixed now. A non-daemon thread can continue its execution even after the main thread has exited.
