### ISSUE TITLE
[BUG]: Measurements do not start because of sun elevation too low although it is not too low

### ISSUE THREAD

**Issue by csam1853** [tum-esm/pyra#208]
### Descriptions

Measurements should start at 11° degrees sun elevation, however even with Pyra showing values above 11° in the overview menu Helios does not start working because of sun elevation too low.

### Pyra Version

4.1.0

**Comment by dostuffthatmatters** [comment]
Thank you for reporting! Could you please add the config and the Pyra version?

**Comment by csam1853** [comment]
With the passwords? It is for Ma.

**Comment by dostuffthatmatters** [comment]
That is a config for `4.0.8`. You can just use the "copy config.json" button on the bottom left of the configuration tab. Here it is:

```json
{
    "general": {
        "version": "4.1.0",
        "seconds_per_core_interval": 30,
        "test_mode": false,
        "station_id": "Ma061",
        "min_sun_elevation": 11
    },
    "opus": {
        "em27_ip": "10.10.0.1",
        "executable_path": "C:\\Program Files (x86)\\Bruker\\OPUS_8.2.28\\opus.exe",
        "experiment_path": "C:\\Users\\Public\\Documents\\Bruker\\OPUS_8.2.28\\XPM\\EM27SUNdual_munichcampaign.xpm",
        "macro_path": "C:\\Users\\Public\\Documents\\Bruker\\OPUS_8.2.28\\Macro\\MUC_61.mtx",
        "username": "Admin",
        "password": "OPUS"
    },
    "camtracker": {
        "config_path": "C:\\Program Files (x86)\\CamTracker_3_9_2015_02_03\\CamTrackerConfig.txt",
        "executable_path": "C:\\Program Files (x86)\\CamTracker_3_9_2015_02_03\\CamTracker_3_9_2015_02_03.exe",
        "learn_az_elev_path": "C:\\Program Files (x86)\\CamTracker_3_9_2015_02_03\\LEARN_Az_Elev.dat",
        "sun_intensity_path": "C:\\Program Files (x86)\\CamTracker_3_9_2015_02_03\\SunIntensity.dat",
        "motor_offset_threshold": 10,
        "restart_if_logs_are_too_old": false,
        "restart_if_cover_remains_closed": false
    },
    "error_email": {
        "smtp_host": "postout.lrz.de",
        "smtp_port": 587,
        "smtp_username": "...",
        "smtp_password": "...",
        "sender_address": "...",
        "notify_recipients": true,
        "recipients": "..."
    },
    "measurement_decision": {
        "mode": "manual",
        "manual_decision_result": true,
        "cli_decision_result": false
    },
    "measurement_triggers": {
        "consider_time": false,
        "consider_sun_elevation": false,
        "consider_helios": true,
        "start_time": {
            "hour": 7,
            "minute": 0,
            "second": 0
        },
        "stop_time": {
            "hour": 21,
            "minute": 0,
            "second": 0
        },
        "min_sun_elevation": 8
    },
    "tum_plc": {
        "ip": "10.10.0.4",
        "version": 1,
        "controlled_by_user": false
    },
    "helios": {
        "camera_id": 0,
        "evaluation_size": 15,
        "seconds_per_interval": 6,
        "min_seconds_between_state_changes": 180,
        "edge_pixel_threshold": 2,
        "edge_color_threshold": 40,
        "target_pixel_brightness": 50,
        "save_images_to_archive": false,
        "save_current_image": true
    },
    "upload": {
        "host": "...",
        "user": "...",
        "password": "...",
        "streams": [
            {
                "is_active": true,
                "label": "datalogger",
                "variant": "files",
                "dated_regex": "^%Y-%m-%d.*$",
                "src_directory": "C:\\MESSUNGEN\\datalogger\\dat",
                "dst_directory": "/mnt/em27-upload/muccnet/datalogger/ma",
                "remove_src_after_upload": false
            },
            {
                "is_active": true,
                "label": "interferograms",
                "variant": "directories",
                "dated_regex": "^%Y%m%d$",
                "src_directory": "C:\\MESSUNGEN",
                "dst_directory": "/mnt/em27-upload/muccnet/ifgs/ma",
                "remove_src_after_upload": true
            }
        ]
    }
}
```

**Comment by dostuffthatmatters** [comment]
Here are the logs from Helios:

```log
2023-12-07 08:27:38.776187 UTC+0 - helios - DEBUG - Current sun elevation below minimum, sleeping 5 minutes
...
2023-12-07 08:32:42.835238 UTC+0 - helios - DEBUG - determined available exposures: [-13, -12, -11, -10, -9, -8, -7, -6, -5, -4, -3, -2, -1]
...
2023-12-07 08:32:59.033284 UTC+0 - helios - DEBUG - exposure results: [ExposureResult(exposure=-13, means=[29.207, 29.397, 29.411]), ExposureResult(exposure=-12, means=[48.322, 48.35, 48.441]), ExposureResult(exposure=-11, means=[113.152, 113.235, 113.373]), ExposureResult(exposure=-10, means=[144.911, 144.953, 144.871]), ExposureResult(exposure=-9, means=[174.539, 174.581, 174.351]), ExposureResult(exposure=-8, means=[191.548, 191.591, 191.623]), ExposureResult(exposure=-7, means=[229.23, 229.234, 229.237]), ExposureResult(exposure=-6, means=[253.993, 253.993, 253.993]), ExposureResult(exposure=-5, means=[254.0, 254.0, 254.0]), ExposureResult(exposure=-4, means=[254.0, 254.0, 254.0]), ExposureResult(exposure=-3, means=[254.0, 254.0, 254.0]), ExposureResult(exposure=-2, means=[254.0, 254.0, 254.0]), ExposureResult(exposure=-1, means=[254.0, 254.0, 254.0])]
2023-12-07 08:33:00.904115 UTC+0 - helios - INFO - changing exposure: -13 -> -12
2023-12-07 08:33:01.069006 UTC+0 - helios - DEBUG - exposure = -12, edge_fraction = 0.018592
...
```

At 08:27:38 it says that it is still waiting because the sun angle is too low. It is at 10.978. Next time it checks, it is at 11.424 so the thread starts working correctly 5 minutes later at 08:32:42. The edge fraction is around 1.9 % which is below the threshold of 2 %.

You can set Helios to start working earlier by decreasing `config.general.min_sun_elevation`.

**Comment by csam1853** [comment]
> Here are the logs from Helios:
> 
> ```
> 2023-12-07 08:27:38.776187 UTC+0 - helios - DEBUG - Current sun elevation below minimum, sleeping 5 minutes
> ...
> 2023-12-07 08:32:42.835238 UTC+0 - helios - DEBUG - determined available exposures: [-13, -12, -11, -10, -9, -8, -7, -6, -5, -4, -3, -2, -1]
> ...
> 2023-12-07 08:32:59.033284 UTC+0 - helios - DEBUG - exposure results: [ExposureResult(exposure=-13, means=[29.207, 29.397, 29.411]), ExposureResult(exposure=-12, means=[48.322, 48.35, 48.441]), ExposureResult(exposure=-11, means=[113.152, 113.235, 113.373]), ExposureResult(exposure=-10, means=[144.911, 144.953, 144.871]), ExposureResult(exposure=-9, means=[174.539, 174.581, 174.351]), ExposureResult(exposure=-8, means=[191.548, 191.591, 191.623]), ExposureResult(exposure=-7, means=[229.23, 229.234, 229.237]), ExposureResult(exposure=-6, means=[253.993, 253.993, 253.993]), ExposureResult(exposure=-5, means=[254.0, 254.0, 254.0]), ExposureResult(exposure=-4, means=[254.0, 254.0, 254.0]), ExposureResult(exposure=-3, means=[254.0, 254.0, 254.0]), ExposureResult(exposure=-2, means=[254.0, 254.0, 254.0]), ExposureResult(exposure=-1, means=[254.0, 254.0, 254.0])]
> 2023-12-07 08:33:00.904115 UTC+0 - helios - INFO - changing exposure: -13 -> -12
> 2023-12-07 08:33:01.069006 UTC+0 - helios - DEBUG - exposure = -12, edge_fraction = 0.018592
> ...
> ```
> 
> At 08:27:38 it says that it is still waiting because the sun angle is too low. It is at 10.978. Next time it checks, it is at 11.424 so the thread starts working correctly 5 minutes later at 08:32:42. The edge fraction is around 1.9 % which is below the threshold of 2 %.
> 
> You can set Helios to start working earlier by decreasing `config.general.min_sun_elevation`.

Nevertheless I had to switch to manual mode to start the measurements (all other stations already measured (Pyra 4.0.8.)). Could be connected to the 5 minutes waiting time, or the dome being dirty, or the Helios spin up time, or sun elevation mismatch? Finally, there is a noticeable difference between the Pyra versions starting the measurements.
